theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 40

[[block]]
block = "net"
device = "wlp2s0"
format = "{ssid} | {ip} {speed_down;K*b}"
interval = 5

[[block]]
block = "backlight"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization} {frequency}"

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
on_click = "zenity --calendar"

[[block]]
block = "pacman"
interval = 600
format = "{pacman} updates available"
format_singular = "{pacman} update available"
format_up_to_date = "system up to date"
critical_updates_regex = "(linux|linux-lts|linux-zen)"
# pop-up a menu showing the available updates. Replace wofi with your favourite menu command.
on_click = "fakeroot pacman -Qu --dbpath /tmp/checkup-db-yourusername/ | dmenu"
