theme = "solarized-dark"

icons = "awesome"

[[block]]
block = "focused_window"
max_width = 21

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
ip = true
speed_up = false
graph_up = true
interval = 5

[[block]]
block = "backlight"

[[block]]
block = "memory"
format_mem = "{Mum}MB/{MTm}MB({Mup}%)"
format_swap = "{SUm}MB/{STm}MB({SUp}%)"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}% {frequency}GHz"

[[block]]
block = "sound"

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}% {time}"

[[block]]
block = "time"
format = "%Y-%m-%d %a"
on_click = "evolution"
[[block]]
block = "time"
format = "%R"
on_click = "zenity --calendar"

[[block]]
block = "pacman"
interval = 10
