theme = "solarized-dark"

icons = "awesome"

[[block]]
block = "focused_window"
max_width = 200

[[block]]
block = "net"
device = "enp0s31f6"
ssid = true
ip = true
speed_up = false
graph_up = true
interval = 5
